export interface InvidiousThumbnail {
  quality: string;
  url: string;
  width?: number;
  height?: number;
}

/** Minimal shape shared by search results, playlist entries and video details. */
export interface InvidiousLikeVideo {
  videoId: string;
  title: string;
  author?: string;
  authorId?: string;
  authorUrl?: string;
  lengthSeconds?: number;
  videoThumbnails?: InvidiousThumbnail[];
  liveNow?: boolean;
}

export interface InvidiousFormatStream {
  url: string;
  itag: string;
  type: string;
  quality: string;
  bitrate?: string;
  container: string;
  encoding: string;
  qualityLabel: string;
  resolution: string;
  size?: string;
}

export interface InvidiousAdaptiveFormat {
  index: string;
  bitrate: string;
  init: string;
  url: string;
  itag: string;
  type: string;
  clen: string;
  lmt: string;
  projectionType: string;
  container: string;
  encoding: string;
  qualityLabel?: string;
  resolution?: string;
  fps: number;
  audioQuality?: string;
  audioSampleRate?: string;
  audioChannels?: string;
}

export interface InvidiousAudioStream {
  url: string;
  itag?: string;
  container?: string;
  encoding?: string;
  bitrate?: string;
  quality?: string;
}

export interface InvidiousMusicTrack {
  song: string;
  artist: string;
  album: string;
  license: string;
}

export interface InvidiousVideo extends InvidiousLikeVideo {
  type?: string;
  author: string;
  description?: string;
  descriptionHtml?: string;
  published?: number;
  publishedText?: string;
  keywords?: string[];
  viewCount?: number;
  likeCount?: number;
  dislikeCount?: number;
  premium?: boolean;
  genre?: string;
  genreUrl?: string;
  formatStreams?: InvidiousFormatStream[];
  adaptiveFormats?: InvidiousAdaptiveFormat[];
  audioStreams?: InvidiousAudioStream[];
  hlsUrl?: string | null;
  dashUrl?: string;
  musicTracks?: InvidiousMusicTrack[];
  recommendedVideos?: InvidiousVideo[];
}

export interface InvidiousSearchResult extends InvidiousVideo {
  type: "video" | "playlist" | "channel" | "hashtag";
  playlistId?: string;
  playlistThumbnail?: string;
  videoCount?: number;
  videos?: InvidiousLikeVideo[];
  autoGenerated?: boolean;
  subCount?: number;
  url?: string;
  channelCount?: number;
}

export interface InvidiousPlaylist {
  title: string;
  playlistId: string;
  author: string;
  authorId?: string;
  authorThumbnails?: InvidiousThumbnail[];
  description?: string;
  descriptionHtml?: string;
  videoCount: number;
  viewCount?: number;
  viewCountText?: string;
  updated?: number;
  videos: InvidiousLikeVideo[];
}
